### ISSUE TITLE
how to save complete map by 'rosservice '

### ISSUE THREAD

**Issue by liangyongshi** [PRBonn/vdbfusion_ros#5]
I use the ros-version vdbfusion to generate map on kitti, however, when I use the 'rosservice call /save_vdb_volume '/xxx/' ' to save map, only partial map was generated.  
How to save the complete map?

**Comment by liangyongshi** [comment]
When I use the 'rosservice call /save_vdb_volume '/xxx/' ' to save map, only partial map was generated.
How to save the complete map?

**Comment by Naketano** [comment]
Hi
I have the same problem? How did you fix it?

**Comment by liangyongshi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到您的邮件，无法亲自回复，还请见谅。
