### ISSUE TITLE
'external_sophus-download' failed

### ISSUE THREAD

**Issue by Z-Jeff** [PRBonn/vdbfusion_ros#6]
When I run `catkin_make `, there exits an error:
`vdbfusion_ros/CMakeFiles/external_sophus.dir/build.make:97: recipe for target 'vdbfusion_ros/sophus/src/external_sophus-stamp/external_sophus-download' failed
`
How can I fix this?

**Comment by nachovizzo** [comment]
Please check if it works now :)
